references:
  - J.G. Hust and A.B. Lankford,
    Thermal Conductivity of Aluminum, Copper, Iron, and Tungsten from 1K to the Melting Point,
    US Department of Commerce, Boulder, Colorado, 1984,
    fit to Tab. 3.4.1 (RRR=1000, T_min=200K, T_max=900K)
  - https://www.engineeringtoolbox.com/specific-heat-metals-d_152.html

output: [T]

K_11: 237.36
K_11,T: 8.952e-3
K_11,T^2: 2.650e-5
K_11,T^3: -5.687e-7
K_11,T^4: 6.407e-10

T_ref: 293.15

C_p: 910.0
