references:
  - Y.S. Touloukian et al.,
    TPRC Data Series Volume 1. Thermal conductivity - metallic elements and alloys,
    IFI/Plenum, 1970,
    fit to Tab. 35R (T_min=80K, T_max=500K)
  - https://www.engineeringtoolbox.com/specific-heat-metals-d_152.html

output: [T]

K_11: 93.11
K_11,T: -8.719e-2
K_11,T^2: -3.793e-4
K_11,T^3: -4.003e-6
K_11,T^4: 2.676e-8

T_ref: 293.15

C_p: 440.0
