type: Hooke

references:
  - S.M. Collard and R.B. McLellan,
    Acta Metallurgica et Materialia 40:699-702, 1992,
    https://doi.org/10.1016/0956-7151(92)90011-3

C_11: 373.42e+9
C_11,T: -8.929e+7
C_11,T^2: -1.298e+5
C_11,T^3: 1.2807e+2
C_11,T^4: -4.6114e-2

C_12: 241.74e+9
C_12,T: 5.705e+7
C_12,T^2: 0.4511e+5
C_12,T^3: -0.4860e+2
C_12,T^4: 1.446e-2

C_44: 77.65e+9
C_44,T: -1.342e+7
C_44,T^2: -0.1493e+5
C_44,T^3: 0.1260e+2
C_44,T^4: -0.6470e-2

T_ref: 0
