type: Hooke

references:
  - F.H. Featherston and J.R. Neighbours,
    Physical Review 130(4):1324-1333, 1963,
    https://doi.org/10.1103/PhysRev.130.1324,
    fit to Tab. III (T_min=100K, T_max=300K)

C_11: 524.3e+9
C_11,T: -4.794e+7

C_12: 205.1e+9
C_12,T: -2.836e+6

C_44: 160.7e+9
C_44,T: -1.269e+7

T_ref: 293.15
