type: thermalexpansion

references:
  - https://commons.wikimedia.org/wiki/File:Coefficient_dilatation_lineique_aciers.svg,
    fit to Scilab code for generating the image (T_min=100ºC, T_max=400ºC)

Alpha_11: 10.1e-6
Alpha_11,T: 5.0e-9

T_ref: 293.15
