type: phenopowerlaw

references:
  - C. Zambaldi et al.,
    Journal of Materials Research 27(1):356-367, 2021,
    https://doi.org/10.1557/jmr.2011.334
  - L. Wang et al.,
    Acta Materialia 132:598-610, 2017,
    https://doi.org/10.1016/j.actamat.2017.05.015

output: [xi_sl, gamma_sl]

N_sl: [3, 3, 0, 12]   # basal, prism, -, 1. pyr<c+a>

dot_gamma_0_sl: [0.001, 0.001, 0.0, 0.001]
n_sl: [20, 20, 1, 20]
a_sl: [2.0, 2.0, 1.0, 2.0]

# C. Zambaldi et al.:
xi_0_sl:   [0.349e+9, 0.15e+9, 0.0, 1.107e+9]
xi_inf_sl: [0.568e+9, 1.50e+9, 0.0, 3.420e+9]
# L. Wang et al. :
# xi_0_sl:   [127.e+6, 96.e+6, 0.0, 240.e+6]

h_0_sl-sl: [0.2e+9, 0.2e+9, 0.0, 0.2e+9]
h_sl-sl: [+1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0, -1.0, -1.0,
          -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0,  1.0,
          +1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,
          +1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,
          +1.0,  1.0,  1.0,  1.0,  1.0,  1.0] # unused entries are indicated by -1.0
